definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Project:
    properties:
      category:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        description: Explicitly specify the type to be uuid
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/project:
    get:
      consumes:
      - application/json
      description: Get all existing projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Project'
            type: array
      tags:
      - Projects
    post:
      consumes:
      - application/json
      description: Create a Project
      parameters:
      - description: Title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: Category
        in: body
        name: category
        required: true
        schema:
          type: string
      - description: Description
        in: body
        name: description
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      tags:
      - Project
  /api/project/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a project by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - Project
    get:
      consumes:
      - application/json
      description: Get one project by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      tags:
      - Project
    post:
      consumes:
      - application/json
      description: Update a Project by ID
      parameters:
      - description: Title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: Category
        in: body
        name: category
        required: true
        schema:
          type: string
      - description: Description
        in: body
        name: description
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      tags:
      - Project
swagger: "2.0"
